import type { CementSpot, ActiveCooldown } from '../types/map';

const SPOTS_STORAGE_KEY = 'fivem_cement_spots_v4';
const COOLDOWNS_STORAGE_KEY = 'fivem_cement_cooldowns_v4';

export function loadSpotsFromStorage(): CementSpot[] | null {
  try {
    // Clean up older version keys if present
    localStorage.removeItem('fivem_cement_spots_v1');
    localStorage.removeItem('fivem_cement_spots_v2');
    localStorage.removeItem('fivem_cement_spots_v3');

    const raw = localStorage.getItem(SPOTS_STORAGE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed;
    }
  } catch (err) {
    console.error('Failed to load spots from storage:', err);
  }
  return null;
}

export function saveSpotsToStorage(spots: CementSpot[]): void {
  try {
    localStorage.setItem(SPOTS_STORAGE_KEY, JSON.stringify(spots));
  } catch (err) {
    console.error('Failed to save spots to storage:', err);
  }
}

export function clearAllSpotsFromStorage(): void {
  try {
    localStorage.removeItem(SPOTS_STORAGE_KEY);
    localStorage.removeItem(COOLDOWNS_STORAGE_KEY);
    localStorage.removeItem('fivem_cement_spots_v1');
    localStorage.removeItem('fivem_cement_spots_v2');
    localStorage.removeItem('fivem_cement_spots_v3');
  } catch (err) {
    console.error('Failed to clear spots from storage:', err);
  }
}

export function loadCooldownsFromStorage(): ActiveCooldown[] {
  try {
    const raw = localStorage.getItem(COOLDOWNS_STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      const now = Date.now();
      // Keep only cooldowns that are still active or recently expired
      return parsed.filter((c: ActiveCooldown) => c.expiresAt > now - 60000);
    }
  } catch (err) {
    console.error('Failed to load cooldowns from storage:', err);
  }
  return [];
}

export function saveCooldownsToStorage(cooldowns: ActiveCooldown[]): void {
  try {
    localStorage.setItem(COOLDOWNS_STORAGE_KEY, JSON.stringify(cooldowns));
  } catch (err) {
    console.error('Failed to save cooldowns to storage:', err);
  }
}

export function exportSpotsToJSON(spots: CementSpot[], filename = 'fivem_cement_spots.json'): void {
  const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(spots, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', dataStr);
  downloadAnchor.setAttribute('download', filename);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

export function parseImportedSpots(jsonString: string): CementSpot[] {
  const parsed = JSON.parse(jsonString);
  if (!Array.isArray(parsed)) {
    throw new Error('รูปแบบไฟล์ JSON ไม่ถูกต้อง (ต้องเป็น Array ของหมุด)');
  }
  return parsed.map((item, index) => {
    if (typeof item.x !== 'number' || typeof item.y !== 'number') {
      throw new Error(`หมุดลำดับที่ ${index + 1} ไม่มีพิกัด X หรือ Y ที่ถูกต้อง`);
    }
    return {
      id: item.id || `spot-${Date.now()}-${index}`,
      name: item.name || `จุดจกปูน #${index + 1}`,
      category: item.category || 'cement_mine',
      x: item.x,
      y: item.y,
      z: item.z ?? 30.0,
      postal: item.postal || '',
      cooldownMinutes: item.cooldownMinutes ?? 10,
      yieldDescription: item.yieldDescription || '',
      requiredItems: Array.isArray(item.requiredItems) ? item.requiredItems : [],
      notes: item.notes || '',
      color: item.color || '#f59e0b',
      icon: item.icon || undefined,
      createdAt: item.createdAt || Date.now(),
      updatedAt: item.updatedAt || Date.now(),
    };
  });
}

export function formatFiveMCommand(spot: CementSpot): string {
  const z = spot.z !== undefined ? spot.z.toFixed(1) : '30.0';
  return `/tp ${spot.x.toFixed(1)} ${spot.y.toFixed(1)} ${z}`;
}

export function formatFiveMVector(spot: CementSpot): string {
  const z = spot.z !== undefined ? spot.z.toFixed(2) : '30.0';
  return `vec3(${spot.x.toFixed(2)}, ${spot.y.toFixed(2)}, ${z})`;
}

export function formatFiveMLuaTable(spots: CementSpot[]): string {
  const lines = [
    '-- FiveM Cement Spots Configuration',
    '-- Generated by FiveM Cement Map Tracker',
    'Config = Config or {}',
    'Config.CementSpots = {',
  ];

  spots.forEach((spot) => {
    const z = spot.z !== undefined ? spot.z.toFixed(2) : '30.0';
    lines.push(`    {`);
    lines.push(`        name = "${spot.name}",`);
    lines.push(`        category = "${spot.category}",`);
    lines.push(`        coords = vector3(${spot.x.toFixed(2)}, ${spot.y.toFixed(2)}, ${z}),`);
    if (spot.postal) lines.push(`        postal = "${spot.postal}",`);
    if (spot.cooldownMinutes) lines.push(`        cooldown = ${spot.cooldownMinutes * 60}, -- seconds`);
    lines.push(`    },`);
  });

  lines.push('}');
  return lines.join('\n');
}
